# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'ZDToolBoxSwiftDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # https://github.com/realm/SwiftLint/blob/main/README_CN.md
  # 规则： https://realm.github.io/SwiftLint/rule-directory.html
  pod 'SwiftLint', '~> 0.57'
  # 规则： https://github.com/nicklockwood/SwiftFormat/blob/main/Rules.md
  pod 'SwiftFormat/CLI', '~> 0.54'
  
  # Pods for ZDToolBoxSwiftDemo
  pod 'ZDToolBoxSwift', :path => '../ZDToolBoxSwift.podspec'

  target 'ZDToolBoxSwiftDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZDToolBoxSwiftDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
