# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ZDToolBoxSwiftDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for ZDToolBoxSwiftDemo
  pod 'ZDToolBoxSwift', :path => '../ZDToolBoxSwift.podspec'

  target 'ZDToolBoxSwiftDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZDToolBoxSwiftDemoUITests' do
    # Pods for testing
  end

end
