# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ZDSwiftToolKitDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for ZDSwiftToolKitDemo
  pod 'ZDToolBoxSwift', :path => '../ZDToolBoxSwift.podspec'

  target 'ZDSwiftToolKitDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZDSwiftToolKitDemoUITests' do
    # Pods for testing
  end

end
